#pragma once
#include <iostream>

void exploreCampground();
void runAndSetup();
void continueExploring();
void seekHelp();
void explainSound();
void observeCarefully();
void prepareForBed();
void questionSound();
void findMyWayBack();
void shadowAppearance();
void fightBack();
void runAway();
void confrontSound();
void goingToSleep();
void sleepingTime();
void noSleep();
void goBackToSleep();
void wakeFriend();
void goingBackToSleep();
void plannedOut();
void tryConvincing();
void tellWhileRunning();
void tellLater();
void haveHimBeileveYou();
void betrayalToFriend();
void keepPromise();
void brokenPromise();
void rightNow();
void inTheMorning();
void informRightNow();
void informLater();
void refuseSleep();
void nowSleep();