#pragma once
#include "horror_branch1.cpp"
#include <iostream>
using namespace std;
void ending8();
void ending7();
void ending6();
void ending5();
void ending4();
void ending3();
void ending2();
void ending1();
void fork3B();
void fork3A();
void fork2D();
void fork2C();
void fork2B();
void fork2A();
void fork1B();
void fork1A();
void start();